
import { build } from "bun";
import dts from "bun-plugin-dts";

const fnRemoveComments = function() {
    const filesToProcess = [
        { name: 'index.cjs', comment: '// @bun @bun-cjs' },
        { name: 'index.mjs', comment: '// @bun' },
        { name: 'index.d.ts', comment: '// Generated by dts-bundle-generator v9.5.1' }
    ];
    for ( const { name, comment } of filesToProcess ) {
        const filePath = `./dist/${name}`;
        try {
            const content = await Bun.file(filePath).text();
            const lines = content.split('\n');
            if (lines[0].trim() === comment) {
                lines.shift();
                while (lines.length > 0 && lines[0].trim() === '') {
                    lines.shift();
                }
                const newContent = lines.join('\n');
                await Bun.write( filePath, newContent );
            }
        } catch (error) {
            console.error(`Error processing ${filePath}:`, error);
        }
    }
}

await build({
    entrypoints: ['./src/index.ts'],
    plugins: [ dts() ],
    minify: {
        identifiers: false,
        whitespace: true,
        syntax: true
    },
    naming: 'index.mjs',
    sourcemap: 'none',
    outdir: 'dist',
    format: 'esm',
    target: 'bun'
})

await build({
    entrypoints: ['./src/index.ts'],
    minify: {
        identifiers: false,
        whitespace: true,
        syntax: true
    },
    naming: 'index.cjs',
    sourcemap: 'none',
    outdir: 'dist',
    format: 'cjs',
    target: 'bun'
})

await fnRemoveComments()
